# Build Spec for AWS CodeBuild CI

version: 0.2

phases:
  install:
    commands:
      - python scripts/install_dependencies.py --cuda=cu101

  build:
    commands:
      - python torchserve_sanity.py
      - cd serving-sdk/ && mvn clean install -q && cd ../